# Master list of the 200 SEO pages: (category, slug, working title, angle)
IND = [  # /industries/<slug>/  — 50
("trucking","Trucking Company Funding","fuel/driver costs vs 30-90 day broker pay; owner-operators vs fleets"),
("restaurants","Restaurant Funding","equipment, renovations, card-heavy revenue, seasonality"),
("retail-stores","Retail Store Funding","inventory cycles, holiday stocking, foot-traffic swings"),
("construction","Construction Company Funding","project draws, retainage, materials, payroll between milestones"),
("hvac","HVAC Business Funding","seasonal demand spikes, van fleets, equipment inventory, service agreements"),
("plumbing","Plumbing Business Funding","emergency-call economics, vans, tooling, hiring licensed techs"),
("electrical-contractors","Electrical Contractor Funding","bid bonds, materials price swings, commercial job cash gaps"),
("roofing","Roofing Company Funding","storm season surges, insurance-claim payment delays, crews"),
("landscaping","Landscaping Business Funding","spring ramp-up, equipment, winter slowdown/snow removal pivot"),
("auto-repair-shops","Auto Repair Shop Funding","lifts, diagnostic tools, parts inventory, bay expansion"),
("medical-practices","Medical Practice Funding","insurance reimbursement lag, EHR, equipment, new providers"),
("dental-practices","Dental Practice Funding","imaging/chairs, build-outs, insurance lag, associate hiring"),
("chiropractors","Chiropractic Practice Funding","equipment, marketing to new patients, PI-case payment delays"),
("veterinary-clinics","Veterinary Clinic Funding","surgical/imaging equipment, boarding expansion, staffing"),
("pharmacies","Independent Pharmacy Funding","PBM reimbursement timing, inventory, compounding equipment"),
("hair-salons","Hair Salon Funding","stations, build-outs, product inventory, booth vs commission"),
("barbershops","Barbershop Funding","chairs, second location, POS, walk-in volatility"),
("spas-and-wellness","Spa & Wellness Center Funding","treatment equipment, memberships, renovations"),
("gyms-and-fitness","Gym & Fitness Studio Funding","equipment leases vs buy, membership revenue, January surge"),
("ecommerce","E-commerce Business Funding","inventory ahead of Q4, ad spend ROAS, marketplace payout timing"),
("wholesale-distribution","Wholesale & Distribution Funding","large POs, net-60 customers, warehouse, freight"),
("manufacturing","Manufacturing Company Funding","raw materials, machinery, order backlog, PO financing"),
("staffing-agencies","Staffing Agency Funding","weekly payroll vs net-30/60 client invoices, factoring"),
("cleaning-services","Cleaning & Janitorial Business Funding","commercial contracts, supplies, crews, vehicles"),
("it-services","IT Services & MSP Funding","hardware for client projects, recurring contracts, hiring engineers"),
("marketing-agencies","Marketing Agency Funding","client retainers, contractor costs, slow-paying clients"),
("law-firms","Law Firm Funding","contingency case costs, long settlement timelines, staffing"),
("accounting-firms","Accounting & Bookkeeping Firm Funding","tax-season staffing, software, acquiring books of business"),
("real-estate-brokerages","Real Estate Brokerage Funding","commission timing, agent recruiting, marketing"),
("property-management","Property Management Company Funding","maintenance float, software, growth via new doors"),
("hotels-and-motels","Hotel & Motel Funding","PIP renovations, seasonal occupancy, FF&E"),
("bars-and-nightclubs","Bar & Nightclub Funding","liquor inventory, sound/lighting, renovations, weekend-heavy revenue"),
("coffee-shops","Coffee Shop & Cafe Funding","espresso equipment, second location, thin margins"),
("bakeries","Bakery Funding","ovens, wholesale accounts, holiday surges"),
("food-trucks","Food Truck Funding","truck build/repair, commissary, event season"),
("catering","Catering Business Funding","deposits vs upfront costs, vans, event seasonality"),
("convenience-stores","Convenience & Grocery Store Funding","inventory turns, coolers, lottery/EBT cash timing"),
("liquor-stores","Liquor Store Funding","high-value inventory, holiday stocking, distributor terms"),
("gas-stations","Gas Station Funding","fuel deliveries, c-store inventory, pump upgrades"),
("daycare-centers","Daycare & Child Care Center Funding","licensing upgrades, staff ratios, subsidy payment delays"),
("tutoring-and-education","Tutoring & Education Business Funding","back-to-school ramp, curriculum, locations"),
("home-health-care","Home Health Care Agency Funding","Medicaid/insurance billing lag, caregiver payroll"),
("security-companies","Security Company Funding","guard payroll, contracts, vehicles, licensing"),
("event-and-wedding-businesses","Event & Wedding Business Funding","deposits, rentals inventory, peak-season staffing"),
("printing-and-signs","Printing & Sign Company Funding","large-format equipment, materials, B2B terms"),
("florists","Florist Funding","perishable inventory, Valentine's/Mother's Day spikes, delivery vans"),
("pet-grooming","Pet Grooming & Boarding Funding","mobile grooming vans, kennels, expansion"),
("towing-companies","Towing Company Funding","wreckers/flatbeds, motor-club payment timing, insurance"),
("courier-and-logistics","Courier & Last-Mile Logistics Funding","vans, contractor pay, contract onboarding"),
("farms-and-agriculture","Farm & Agriculture Business Funding","planting-to-harvest gap, equipment, livestock feed"),
]
FUND = [  # /funding/<slug>/ — 30
("merchant-cash-advance","Merchant Cash Advance","how MCAs work, factor rates, holdback, who they fit"),
("working-capital-loans","Working Capital Loans","short-term operating capital; vs MCA vs LOC"),
("small-business-loans","Small Business Loans","term structures, what underwriters review"),
("short-term-business-loans","Short-Term Business Loans","3-24 month terms, daily/weekly payments, uses"),
("business-line-of-credit","Business Line of Credit","revolving draws, interest only on used funds"),
("equipment-financing","Equipment Financing","equipment as collateral, loan vs lease, Section 179 mention (consult CPA)"),
("invoice-factoring","Invoice Factoring","selling receivables, recourse vs non-recourse, advance rates"),
("revenue-based-financing","Revenue-Based Financing","payments flex with revenue; vs MCA"),
("sba-loans","SBA Loans Explained","7(a)/504 basics, timelines; when faster options make sense as a bridge"),
("bad-credit-business-loans","Business Funding with Bad Credit","revenue-first underwriting, realistic expectations, cost"),
("startup-business-funding","Startup Business Funding","what's realistic under 6-12 months in business"),
("same-day-business-funding","Same-Day Business Funding","what makes speed possible, docs ready, trade-offs"),
("inventory-financing","Inventory Financing","stocking ahead, inventory-backed vs unsecured options"),
("payroll-funding","Payroll Funding","bridging payroll gaps safely"),
("seasonal-business-funding","Seasonal Business Funding","pre-season capital, payment structures that fit"),
("business-expansion-loans","Business Expansion Loans","second locations, build-outs, ROI planning"),
("mca-consolidation","MCA Consolidation","consolidating multiple advances, when it helps vs hurts"),
("purchase-order-financing","Purchase Order Financing","funding supplier costs for confirmed orders"),
("business-term-loans","Business Term Loans","fixed schedules, longer horizons, qualification"),
("unsecured-business-loans","Unsecured Business Loans","no specific collateral, personal guarantees explained"),
("business-cash-advance-vs-loan","Business Cash Advance vs. Loan","side-by-side decision guide"),
("fast-business-loans","Fast Business Loans","fast vs cheap trade-off, how to move quickly"),
("low-doc-business-loans","Low-Documentation Business Funding","bank-statement-based underwriting"),
("commercial-vehicle-financing","Commercial Vehicle Financing","trucks, vans, trailers"),
("restaurant-equipment-financing","Restaurant Equipment Financing","kitchen gear, hoods, POS"),
("medical-equipment-financing","Medical Equipment Financing","imaging, chairs, lasers"),
("construction-equipment-financing","Construction Equipment Financing","excavators, skid steers, used vs new"),
("emergency-business-funding","Emergency Business Funding","sudden repairs, losses; avoiding panic decisions"),
("business-funding-for-women","Business Funding for Women Entrepreneurs","options, grants vs financing, preparation"),
("minority-business-funding","Funding for Minority-Owned Businesses","programs, CDFIs, private financing options"),
]
USE = [  # /use-cases/<slug>/ — 30
("hire-employees","Funding to Hire Employees","cost of a hire, ramp time, payback math"),
("buy-inventory","Funding to Buy Inventory","bulk discounts, turn rates, avoiding overstock"),
("open-a-second-location","Funding a Second Location","site costs, ramp period, risk checks"),
("renovate-your-business","Funding Business Renovations","remodel ROI, permits, staying open during work"),
("marketing-and-advertising","Funding Marketing & Advertising","CAC/payback, testing before scaling"),
("cover-payroll","Funding to Cover Payroll","bridging gaps, root causes, legal obligations"),
("pay-tax-bills","Funding Business Tax Bills","IRS payment plans vs financing (consult a tax pro)"),
("emergency-repairs","Funding Emergency Repairs","downtime cost vs financing cost"),
("buy-a-commercial-truck","Funding a Commercial Truck Purchase","new vs used, down payment, authority"),
("upgrade-pos-systems","Funding POS & Technology Upgrades","modern POS, payments, PayPilot link"),
("bridge-cash-flow-gaps","Bridging Cash Flow Gaps","receivables timing, forecasting"),
("seasonal-hiring","Funding Seasonal Hiring","peak staffing, timing payments to peak revenue"),
("insurance-premiums","Funding Business Insurance Premiums","premium financing vs working capital"),
("partner-buyout","Funding a Business Partner Buyout","valuation basics, structuring"),
("government-contracts","Funding Government Contract Mobilization","net-30+ gov payments, mobilization costs"),
("buy-equipment","Funding to Buy Equipment","buy vs lease vs finance"),
("expand-product-lines","Funding New Product Lines","testing demand, inventory risk"),
("website-and-ecommerce","Funding a Website or E-commerce Build","digital storefront ROI"),
("hire-a-sales-team","Funding a Sales Team","quota ramp, commission structures"),
("refinance-expensive-debt","Refinancing Expensive Business Debt","when refinancing lowers total cost"),
("take-on-a-big-order","Funding a Large Customer Order","PO vs working capital"),
("relocate-your-business","Funding a Business Relocation","moving costs, downtime, lease deposits"),
("buy-a-business","Funding a Business Acquisition","acquisition financing basics, due diligence"),
("franchise-funding","Franchise Funding","franchise fees, build-out, FDD Item 7"),
("vehicle-fleet-expansion","Funding Fleet Expansion","utilization math, insurance, drivers"),
("software-and-automation","Funding Software & Automation","productivity ROI"),
("trade-show-and-events","Funding Trade Shows & Events","booth costs, lead ROI"),
("security-and-compliance-upgrades","Funding Security & Compliance Upgrades","PCI, cameras, licensing"),
("slow-season-survival","Surviving the Slow Season","planning, cutting vs funding"),
("disaster-recovery","Funding Disaster Recovery","after storms/fires; insurance gaps; SBA disaster loans mention"),
]
BLOG = [  # /blog/<slug>/ — 90
("factor-rate-explained","What Is a Factor Rate? MCA Pricing Explained","how to convert to total payback; why it isn't APR"),
("total-payback-vs-apr","Total Payback vs. APR: Comparing Funding Offers","apples-to-apples comparison method"),
("how-mca-holdback-works","How MCA Holdback Percentages Work","split vs ACH remittance"),
("daily-vs-weekly-payments","Daily vs. Weekly Payments: Which Is Better?","cash flow effects"),
("bank-statements-underwriters-review","What Underwriters Look For in Your Bank Statements","deposits, balances, NSFs, other lenders"),
("nsf-and-negative-days","NSFs and Negative Days: Why They Matter","fixing patterns before applying"),
("mca-stacking-risks","The Real Risks of MCA Stacking","multiple positions, payment burden"),
("improve-business-funding-approval-odds","10 Ways to Improve Your Funding Approval Odds","practical prep"),
("time-in-business-requirements","Time in Business Requirements Explained","why lenders care"),
("minimum-revenue-for-business-funding","Revenue Requirements for Business Funding","how revenue drives amounts (no invented minimums—say varies)"),
("soft-pull-vs-hard-pull","Soft Pull vs. Hard Pull Credit Checks","what each means for owners"),
("personal-guarantee-explained","Personal Guarantees Explained","what you're signing"),
("ucc-filings-explained","What Is a UCC Filing?","UCC-1 basics"),
("confession-of-judgment","Confessions of Judgment: What Owners Should Know","state law varies; read contracts"),
("early-payoff-discounts","Early Payoff Discounts on Merchant Cash Advances","ask before signing"),
("reconciliation-clause-mca","The MCA Reconciliation Clause","adjusting payments when sales drop"),
("predatory-lending-red-flags","Red Flags of Predatory Business Lenders","protect yourself"),
("how-to-compare-funding-offers","How to Compare Business Funding Offers","checklist"),
("business-cash-flow-forecasting","Cash Flow Forecasting for Small Businesses","13-week forecast how-to"),
("seasonal-cash-flow-planning","Planning Cash Flow for a Seasonal Business","reserve building"),
("working-capital-formula","Working Capital: Formula and Why It Matters","current assets - liabilities"),
("cash-conversion-cycle","The Cash Conversion Cycle Explained","DIO+DSO-DPO"),
("accounts-receivable-tips","How to Get Paid Faster: Accounts Receivable Tips","invoicing hygiene"),
("business-credit-score-basics","Business Credit Scores: The Basics","D&B, Experian, Equifax business"),
("build-business-credit","How to Build Business Credit","steps"),
("separate-business-personal-finances","Why You Must Separate Business and Personal Finances","underwriting + legal"),
("business-bank-account-tips","Business Banking Habits That Help Your Funding","balances, deposits"),
("documents-needed-for-business-funding","Documents You Need for Business Funding","complete checklist"),
("how-long-business-funding-takes","How Long Does Business Funding Take?","timeline by product"),
("what-is-a-funding-broker","What Does a Business Funding Broker Do?","how brokers work, transparency"),
("broker-vs-direct-lender","Broker vs. Direct Lender: Pros and Cons","when each fits"),
("sba-vs-alternative-lending","SBA Loans vs. Alternative Lending","speed vs cost"),
("line-of-credit-vs-term-loan","Line of Credit vs. Term Loan","choosing"),
("equipment-lease-vs-loan","Equipment Lease vs. Equipment Loan","ownership, tax (consult CPA)"),
("invoice-factoring-vs-mca","Invoice Factoring vs. Merchant Cash Advance","B2B vs card-heavy"),
("credit-card-processing-fees-explained","Credit Card Processing Fees Explained","interchange, assessments, markup; PayPilot by MCCPS"),
("interchange-plus-vs-flat-rate","Interchange-Plus vs. Flat-Rate Processing","which saves more; PayPilot"),
("cash-discount-and-surcharging","Cash Discount Programs and Surcharging","rules vary by state and card brand; PayPilot"),
("pci-compliance-basics","PCI Compliance Basics for Small Businesses","SAQ, fees"),
("reduce-chargebacks","How to Reduce Chargebacks","prevention"),
("choosing-a-pos-system","How to Choose a POS System","features; PayPilot"),
("read-your-merchant-statement","How to Read Your Merchant Processing Statement","effective rate calc; PayPilot audit"),
("contactless-and-tap-to-pay","Contactless & Tap-to-Pay for Small Businesses","adoption, hardware"),
("hidden-processing-fees","Hidden Credit Card Processing Fees to Watch For","PCI non-compliance, batch, monthly minimums"),
("trucking-fuel-costs-cash-flow","Managing Fuel Costs in a Trucking Business","fuel cards, factoring, capital"),
("owner-operator-funding-guide","The Owner-Operator's Guide to Funding","authority, truck, insurance"),
("restaurant-cash-flow-tips","Restaurant Cash Flow: 12 Practical Tips","prime cost, inventory"),
("restaurant-renovation-planning","Planning a Restaurant Renovation Without Closing","phasing"),
("retail-holiday-inventory-planning","Holiday Inventory Planning for Retailers","open-to-buy"),
("contractor-cash-flow-retainage","Contractor Cash Flow and Retainage","managing retainage"),
("medical-practice-reimbursement-gap","Bridging the Insurance Reimbursement Gap","practices"),
("ecommerce-q4-inventory-funding","Funding E-commerce Inventory for Q4","timeline"),
("salon-business-growth","Growing a Salon: When Financing Makes Sense","chairs, products"),
("hvac-off-season-planning","HVAC Off-Season Cash Planning","service agreements"),
("landscaping-winter-cash-flow","Landscaping Cash Flow Through Winter","snow pivot"),
("staffing-agency-payroll-gap","Solving the Staffing Agency Payroll Gap","factoring"),
("construction-bid-cash-needs","Cash Needs When Bidding Bigger Construction Jobs","bonding"),
("is-a-merchant-cash-advance-a-loan","Is a Merchant Cash Advance a Loan?","purchase of future receivables"),
("mca-myths","7 Merchant Cash Advance Myths","balanced"),
("when-not-to-take-funding","When You Should NOT Take Business Funding","honest guide"),
("funding-roi-calculation","How to Calculate the ROI of Business Funding","simple model"),
("debt-service-coverage-ratio","Debt Service Coverage Ratio (DSCR) Explained","formula"),
("business-debt-management","Managing Multiple Business Debts","priority, communication"),
("negotiating-with-lenders","How to Negotiate with Lenders and Funders","levers"),
("business-plan-for-funding","Do You Need a Business Plan to Get Funded?","when and what"),
("startup-funding-options","Startup Funding Options Compared","savings, friends, SBA microloans, revenue-based"),
("grants-vs-loans","Small Business Grants vs. Loans","realistic view"),
("business-credit-cards-vs-loans","Business Credit Cards vs. Business Loans","use cases"),
("ein-and-business-structure","EIN, LLC, S-Corp: Structure and Funding","why structure matters (consult professionals)"),
("tax-liens-and-funding","Can You Get Funding with a Tax Lien?","options, disclosure"),
("funding-after-bankruptcy","Business Funding After Bankruptcy","timelines, expectations"),
("judgments-and-funding","How Judgments Affect Business Funding","disclosure"),
("renewals-and-repeat-funding","Funding Renewals: How Repeat Funding Works","paydown thresholds"),
("prepare-for-funding-call","How to Prepare for Your Funding Specialist Call","questions to ask"),
("questions-to-ask-a-funder","15 Questions to Ask Before Accepting Funding","list"),
("business-emergency-fund","Building a Business Emergency Fund","target months"),
("inflation-small-business-strategies","Small Business Strategies for High Costs","pricing, purchasing"),
("pricing-for-profit","Pricing for Profit: A Small Business Guide","markup vs margin"),
("gross-margin-vs-net-margin","Gross Margin vs. Net Margin","definitions"),
("profit-vs-cash-flow","Why Profitable Businesses Still Run Out of Cash","timing"),
("hiring-your-first-employee","Hiring Your First Employee: The Real Costs","payroll taxes, onboarding (general)"),
("commercial-lease-negotiation","Negotiating a Commercial Lease","TI allowances"),
("second-location-checklist","The Second-Location Readiness Checklist","signals"),
("customer-acquisition-cost","Customer Acquisition Cost and Payback","for funding marketing"),
("ach-explained","How ACH Payments Work for Businesses","debits, timing"),
("business-funding-glossary-guide","Business Funding Terms Every Owner Should Know","narrative glossary"),
("year-end-financial-checklist","Year-End Financial Checklist for Small Businesses","prep"),
("quarterly-tax-planning","Quarterly Estimated Taxes and Cash Flow","set-asides (consult CPA)"),
("bank-statement-loans-explained","Bank Statement Business Loans Explained","underwriting on deposits instead of tax returns"),
("small-business-cybersecurity-payments","Payment Security Basics for Small Businesses","fraud, PCI; PayPilot"),
]
PAGES = [("industries", *x) for x in IND] + [("funding", *x) for x in FUND] + [("use-cases", *x) for x in USE] + [("blog", *x) for x in BLOG]
if __name__ == "__main__":
    import json, collections
    print(len(PAGES), collections.Counter(p[0] for p in PAGES))
    assert len({p[1] for p in PAGES}) == len(PAGES)
    json.dump([{"category": c, "slug": s, "title": t, "angle": a, "url": f"/{c}/{s}/"} for c, s, t, a in PAGES], open("content/manifest.json", "w"), indent=0)
